[tool.poetry]
name = "coastpy"
version = "0.1.0"
description = "Coastal Monitoring with Remote Sensing "
authors = ["Floris Calkoen"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
